### PR TITLE
Add partial documentation and docs infrastructure

### PR DESCRIPTION
**Pull request by arichiardi**
This adds the content and infra that publishes adoc files to Github pages.

### CODE REVIEW

**Comment by paulcoyle** [comment]
All the documentation and configuration LGTM.  However, I find the diagrams a bit confusing.  Would you mind if I suggested some modifications?

**Comment by arichiardi** [comment]
@paulcoyle suggesting an improvement is always welcome!

I am going to CC @mrivas616 cause he has worked on these diagrams and has them locally

**Comment by paulcoyle** [comment]
Actually, on re-reviewing I guess they make sense; I was a bit confused about this circle in the state transitions.  If you have time @mrivas616 - maybe just label the arrow and drop the circle?  Other than that, it is gtg.

**Review by paulcoyle — APPROVED** [review]
Looks good, make a suggestion to @mrivas616 on the state diagram.

**Comment by mrivas616** [comment]
> Actually, on re-reviewing I guess they make sense; I was a bit confused about this circle in the state transitions. If you have time @mrivas616 - maybe just label the arrow and drop the circle? Other than that, it is gtg.

Sounds good, thank you, will do :+1:

**Pull request merged**
